site_name: Showtime-Bro-Demo
site_url: https://Showtimeeee.github.io/mkdocs-demo/
theme:
  name: material
  language: ru  # –ò–ª–∏ –¥—Ä—É–≥–æ–π –Ω—É–∂–Ω—ã–π —è–∑—ã–∫ (–≤–∞–∂–Ω–æ –¥–ª—è –ø–µ—Ä–µ–≤–æ–¥–æ–≤)
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  copyright: "Copyright ¬© 2025 Vadim."
  generator: false  # –°–∫—Ä—ã–≤–∞–µ–º –Ω–∞–¥–ø–∏—Å—å "Made with MkDocs"
  translations:
    toc: "–°–æ–¥–µ—Ä–∂–∞–Ω–∏–µ —Å—Ç—Ä–∞–Ω–∏—Ü—ã"

nav:
  - –ì–ª–∞–≤–Ω–∞—èüçï: index.md
  - –°—Ç–∞—Ç—å–∏üìù: articles.md
  - –ü—Ä–æ–µ–∫—Ç—ãü§ñ: projects/projects.md
  - –î–∏–∞–≥—Ä–∞–º–º—ãüìä: graphs/grafs.md
  - –ê–ª–≥–æ—Ä–∏—Ç–º—ãüë®‚Äçüíª: algorithms/algorithms.md

extra_css:
  - css/extra.css

markdown_extensions:
  - neoteroi.timeline

plugins:
  - search
  - redirects
  - mkdocs-video
  - mermaid2

copyright: Copyright &copy; 2025 <a href="">Vadim</a>.
